const widgetHelpText: Record<string, string> = {
    'work-list': 'Lista de tareas y recordatorios para organizar la sesión.',
    'attendance': 'Registro rápido de asistencia y estado del grupo.',
    'group-generator': 'Crea grupos aleatorios o equilibrados.',
    'calendar': 'Calendario visual para fechas y planificación.',
    'program-guide': 'Guía integrada con el catálogo de widgets y usos.',
    'timer': 'Cuenta atrás para actividades y turnos.',
    'stopwatch': 'Cronómetro para medir tiempos.',
    'metronome': 'Pulso constante para ritmo y dinámicas.',
    'global-clocks': 'Horarios de varias ciudades para comparar.',
    'scientific-calculator': 'Calculadora científica para cálculos avanzados.',
    'unit-converter': 'Conversor de unidades para problemas y prácticas.',
    'latex-markdown': 'Editor de Markdown y LaTeX con fórmulas.',
    'vce-community': 'Catálogo de apps educativas de la comunidad.',
    'comunidad-chatgpt-ia-edu': 'Recursos del proyecto ChatGPT-IA-edu.',
    'edumedia-iag': 'Recursos multimedia educativos con IA generativa.',
    'file-manager': 'Gestiona archivos y carpetas guardados en el navegador.',
    'notepad': 'Bloc de notas rápido para consignas y listas.',
    'drawing-pad': 'Pizarra de dibujo libre y esquemas.',
    'image-carousel': 'Muestra una colección de imágenes.',
    'edimarkweb': 'Procesador Markdown con vista previa y exportación.',
    'html-sandbox': 'Espacio para mostrar contenido HTML.',
    'boardlive': 'Pizarra colaborativa en tiempo real.',
    'iframe': 'Visor web para páginas dentro del escritorio.',
    'local-web': 'Guarda y ejecuta webs locales sin conexión.',
    'file-opener': 'Abre archivos locales (PDF, imágenes, audio, vídeo).',
    'directo-viewer': 'Visor para contenido web o recursos externos.',
    'wikipedia-search': 'Búsqueda rápida en Wikipedia con cambio de idioma.',
    'dice': 'Lanzador de dados 3D para azar.',
    'random-spinner': 'Ruleta aleatoria para sorteos y turnos.',
    'qr-code-generator': 'Genera códigos QR para compartir enlaces.',
    'traffic-light': 'Semáforo visual de estado y actividad.',
    'sound-meter': 'Medidor visual del nivel de ruido.',
    'scoreboard': 'Marcador de puntos para equipos y retos.',
    'directo-vota': 'Votación simple con resultados inmediatos.',
    'directo-escala': 'Escala de valoración para opiniones.',
    'directo-nube': 'Nube de palabras con respuestas cortas.',
    'directo-ideas': 'Lluvia de ideas con votaciones.',
    'directo-muro': 'Muro colaborativo con notas.',
    'directo-ticket': 'Tickets de salida al final de la sesión.',
    'qplay': 'Concurso interactivo con cuestionarios.',
    'tic-tac-toe': 'Tres en raya para repaso rápido.',
    'memory-game': 'Memorama de parejas para practicar conceptos.',
    'sliding-puzzle': 'Puzzle deslizante para lógica y atención.',
    'work-gestures': 'Gestos de trabajo para dinámicas de aula.',
};

export const getWidgetHelpText = (widgetId: string) => widgetHelpText[widgetId] ?? '';
