const widgetHelpText: Record<string, string> = {
    'work-list': 'Lista de tareas y recordatorios para organizar la sesión.',
    'attendance': 'Registro rápido de asistencia y estado del grupo.',
    'group-generator': 'Crea grupos aleatorios o equilibrados.',
    'calendar': 'Calendario visual para fechas y planificación.',
    'program-guide': 'Guía integrada con el catálogo de widgets y usos.',
    'alarm': 'Programación de alarmas por hora o cuenta atrás.',
    'stopwatch': 'Cronómetro para medir tiempos.',
    'metronome': 'Pulso constante para ritmo y dinámicas.',
    'global-clocks': 'Horarios de varias ciudades para comparar.',
    'scientific-calculator': 'Calculadora científica para cálculos avanzados.',
    'unit-converter': 'Conversor de unidades para problemas y prácticas.',
    'markdown-text-editor': 'Editor de textos en formato Markdown y fórmulas en LaTeX. Además de guardarlo en formato Markdown (.md) puedes copiar el código Markdown, copiar el código HTML para pegarlo en otros procesadores de texto y también imprimirlo en PDF.',
    'vce-community': 'Catálogo de apps educativas de la comunidad.',
    'comunidad-chatgpt-ia-edu': 'Recursos del proyecto ChatGPT-IA-edu.',
    'edumedia-iag': 'Recursos multimedia educativos con IA generativa.',
    'file-manager': 'Gestiona archivos y carpetas guardados en el navegador.',
    'notepad': 'Bloc de notas rápido para consignas y listas.',
    'drawing-pad': 'Pizarra de dibujo libre y esquemas.',
    'image-carousel': 'Muestra una colección de imágenes.',
    'html-sandbox': 'Espacio para mostrar contenido HTML.',
    'boardlive': 'Pizarra colaborativa en tiempo real.',
    'iframe': 'Visor web para páginas dentro del escritorio.',
    'local-web': 'Guarda y ejecuta webs locales sin conexión.',
    'file-opener': 'Abre archivos locales (PDF, imágenes, audio, vídeo).',
    'wikipedia-search': 'Búsqueda rápida en Wikipedia con cambio de idioma.',
    'dice': 'Lanzador de dados 3D para azar.',
    'random-spinner': 'Ruleta aleatoria para sorteos y turnos.',
    'qr-code-generator': 'Genera códigos QR para compartir enlaces.',
    'traffic-light': 'Semáforo visual de estado y actividad.',
    'sound-meter': 'Medidor visual del nivel de ruido.',
    'scoreboard': 'Marcador de puntos para equipos y retos.',
    'directo-vota': 'Votación simple con resultados inmediatos.',
    'directo-escala': 'Escala de valoración para opiniones.',
    'directo-nube': 'Nube de palabras con respuestas cortas.',
    'directo-ideas': 'Lluvia de ideas con votaciones.',
    'directo-muro': 'Muro colaborativo con notas.',
    'directo-ticket': 'Tickets de salida al final de la sesión.',
    'qplay': 'Concurso interactivo con cuestionarios.',
    'tic-tac-toe': 'Tres en raya para repaso rápido.',
    'memory-game': 'Memorama de parejas para practicar conceptos.',
    'sliding-puzzle': 'Puzzle deslizante para lógica y atención.',
    'work-gestures': 'Gestos de trabajo para dinámicas de aula.',
};

const widgetHelpKeys: Record<string, string> = {
    'work-list': 'widgets_help.work-list',
    'attendance': 'widgets_help.attendance',
    'group-generator': 'widgets_help.group-generator',
    'calendar': 'widgets_help.calendar',
    'program-guide': 'widgets_help.program-guide',
    'alarm': 'widgets_help.alarm',
    'stopwatch': 'widgets_help.stopwatch',
    'metronome': 'widgets_help.metronome',
    'global-clocks': 'widgets_help.global-clocks',
    'scientific-calculator': 'widgets_help.scientific-calculator',
    'unit-converter': 'widgets_help.unit-converter',
    'markdown-text-editor': 'widgets_help.markdown-text-editor',
    'vce-community': 'widgets_help.vce-community',
    'comunidad-chatgpt-ia-edu': 'widgets_help.comunidad-chatgpt-ia-edu',
    'edumedia-iag': 'widgets_help.edumedia-iag',
    'file-manager': 'widgets_help.file-manager',
    'notepad': 'widgets_help.notepad',
    'drawing-pad': 'widgets_help.drawing-pad',
    'image-carousel': 'widgets_help.image-carousel',
    'html-sandbox': 'widgets_help.html-sandbox',
    'boardlive': 'widgets_help.boardlive',
    'iframe': 'widgets_help.iframe',
    'local-web': 'widgets_help.local-web',
    'file-opener': 'widgets_help.file-opener',
    'wikipedia-search': 'widgets_help.wikipedia-search',
    'dice': 'widgets_help.dice',
    'random-spinner': 'widgets_help.random-spinner',
    'qr-code-generator': 'widgets_help.qr-code-generator',
    'traffic-light': 'widgets_help.traffic-light',
    'sound-meter': 'widgets_help.sound-meter',
    'scoreboard': 'widgets_help.scoreboard',
    'directo-vota': 'widgets_help.directo-vota',
    'directo-escala': 'widgets_help.directo-escala',
    'directo-nube': 'widgets_help.directo-nube',
    'directo-ideas': 'widgets_help.directo-ideas',
    'directo-muro': 'widgets_help.directo-muro',
    'directo-ticket': 'widgets_help.directo-ticket',
    'qplay': 'widgets_help.qplay',
    'tic-tac-toe': 'widgets_help.tic-tac-toe',
    'memory-game': 'widgets_help.memory-game',
    'sliding-puzzle': 'widgets_help.sliding-puzzle',
    'work-gestures': 'widgets_help.work-gestures',
};

export const getWidgetHelpText = (widgetId: string, t?: (key: string) => string) => {
    const key = widgetHelpKeys[widgetId];
    if (key && t) {
        const translated = t(key);
        if (translated && translated !== key) {
            return translated;
        }
    }
    return widgetHelpText[widgetId] ?? '';
};
